application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
     type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  publicHost:
    type: string
    title: Public host name (ON-PREMISE ONLY)
    description: Must be a valid DNS name. For IP addresses add beesdns.com. eg. 139.178.70.46.beesdns.com This is only required for on-premise only. For cloud GKE, skip this field and this is assigned automatically.
    pattern: ^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$
  loadBalancerIp:
    type: string
    title: Load balancer IP (ON-PREMISE ONLY)
    description: This is only required for on-premise only. For cloud GKE, skip this field and this is assigned automatically.
    pattern: ^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
  cjocImage:
    type: string
    description: This is the CloudBees Core Operations Center image.
    default: gcr.io/cje-marketplace-dev/cloudbees-core:2.176.3.2
    x-google-marketplace:
      type: IMAGE
  mmImage:
    type: string
    description: This is the Jenkins Managed Master image.
    default: gcr.io/cje-marketplace-dev/cloudbees-core/cloudbees-core-mm:2.176.3.2
    x-google-marketplace:
      type: IMAGE
  nginxIngressImage:
    type: string
    description: This is an image for the nginx ingress controller.
    default: gcr.io/cje-marketplace-dev/cloudbees-core/nginx-ingress-controller:0.23.0
    x-google-marketplace:
      type: IMAGE
  cloudBeesCoreServiceAccount:
    title: Service account name
    type: string
    description: This is the name of the ServiceAccount that is used to deploy CloudBees Core Operations Center and Jenkins Managed Masters.
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin
  ssd:
    title: SSD storage name
    type: string
    description: This is the name of the SSD storage that will be provisioned.
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD
required:
- name
- namespace
- cjocImage
- mmImage
- cloudBeesCoreServiceAccount
- ssd