application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
     type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  loadBalancerIp:
    type: string
    title: Load Balancer IP (for on-premise only)
    description: This is only required for on-premise only. For GKE cloud, skip this field and an IP is assigned automatically.
    pattern: ^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$
  cjocImage:
    type: string
    description: This is the CloudBees Core Operations Center image.
    default: gcr.io/cje-marketplace-dev/cloudbees-core:2
    x-google-marketplace:
      type: IMAGE
  mmImage:
    type: string
    description: This is the Jenkins Managed Master image.
    default: gcr.io/cje-marketplace-dev/cloudbees-core/cloudbees-core-mm:2
    x-google-marketplace:
      type: IMAGE
  defaultBackendImage:
    type: string
    description: This is an image for the nginx ingress controller.
    default: gcr.io/cje-marketplace-dev/cloudbees-core/defaultbackend:2
    x-google-marketplace:
      type: IMAGE
  nginxIngressImage:
    type: string
    description: This is an image for the nginx ingress controller.
    default: gcr.io/cje-marketplace-dev/cloudbees-core/nginx-ingress-controller:2
    x-google-marketplace:
      type: IMAGE
  cloudBeesCoreServiceAccount:
    title: ServiceAccount Name
    type: string
    description: This is the name of the ServiceAccount that is used to deploy CloudBees Core Operations Center and Jenkins Managed Masters.
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin
  ssd:
    title: SSD Storage Name
    type: string
    description: This is the name of the SSD storage that will be provisioned.
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD
required:
- name
- namespace
- cjocImage
- mmImage
- cloudBeesCoreServiceAccount
- ssd