application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
     type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  cjocImage:
    type: string
    description: This is the CloudBees Core Operations Center image.
    default: gcr.io/cje-marketplace-dev/cloudbees:2
    x-google-marketplace:
      type: IMAGE
  mmImage:
    type: string
    description: This is the Jenkins Managed Master image.
    default: gcr.io/cje-marketplace-dev/cloudbees/cje-mm:2
    x-google-marketplace:
      type: IMAGE
  cloudBeesCoreServiceAccount:
    type: string
    description: This is the name of the ServiceAccount that is used to deploy CloudBees Core Operations Center and Jenkins Managed Masters.
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin
  ssd:
    type: string
    description: This is the name of the SSD storage that will be provisioned.
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD
required:
- name
- namespace
- cjocImage
- mmImage
- cloudBeesCoreServiceAccount
- ssd